"""Data-contract and ETAPA 3 validation rules for M01 inputs."""

from __future__ import annotations

import math
from dataclasses import dataclass

from .loader import M01Inputs


NUMERIC_ROUNDING_TOLERANCE_M = 1e-9

DICTIONARY_COLUMNS = {
    "file",
    "column",
    "description",
    "unit",
    "dtype",
    "nullable",
}

MANIFEST_COUNT_FIELDS = {
    "collar.csv": "n_holes",
    "survey.csv": "n_surveys",
    "assay.csv": "n_assays",
    "lithology.csv": "n_lithology_intervals",
    "density.csv": "n_density_samples",
    "alteration.csv": "n_alteration_intervals",
}

UNIQUE_IDENTIFIER_FIELDS = {
    "assay.csv": "sample_id",
    "density.csv": "density_sample_id",
}

CONTRACT_RULES = {
    "CTR_DICTIONARY_SCHEMA": ("ERROR", "data_dictionary.csv"),
    "CTR_DICTIONARY_ROW": ("ERROR", "data_dictionary.csv"),
    "CTR_DICTIONARY_DUPLICATE": ("ERROR", "data_dictionary.csv"),
    "CTR_DICTIONARY_DEFINITION": ("ERROR", "data_dictionary.csv"),
    "CTR_MANIFEST_FILES": ("ERROR", "release_manifest.json"),
    "CTR_SCHEMA_COLUMN": ("ERROR", "source_table"),
    "CTR_REQUIRED_VALUE": ("ERROR", "source_table"),
    "CTR_VALUE_TYPE": ("ERROR", "source_table"),
    "CTR_VALUE_FINITE": ("ERROR", "source_table"),
    "CTR_MANIFEST_COUNT": ("ERROR", "source_table"),
    "CTR_MANIFEST_IDENTITY": ("ERROR", "source_table"),
    "CTR_STABLE_ID_UNIQUE": ("ERROR", "source_table"),
    "CTR_HOLE_REFERENCE": ("ERROR", "source_table"),
}

VALIDATION_RULES = {
    "COLLAR_HOLE_ID_UNIQUE": ("ERROR", "collar.csv"),
    "COLLAR_FINAL_DEPTH_POSITIVE": ("ERROR", "collar.csv"),
    "COLLAR_COORDINATE_FINITE": ("ERROR", "collar.csv"),
    "SURVEY_HOLE_REFERENCE": ("ERROR", "survey.csv"),
    "SURVEY_DEPTH_NONNEGATIVE": ("ERROR", "survey.csv"),
    "SURVEY_DEPTH_ORDERED": ("ERROR", "survey.csv"),
    "SURVEY_DEPTH_ZERO_STATION": ("ERROR", "survey.csv"),
    "SURVEY_DEPTH_WITHIN_COLLAR": ("ERROR", "survey.csv"),
    "SURVEY_ORIENTATION_FINITE": ("ERROR", "survey.csv"),
    "INTERVAL_FROM_BEFORE_TO_ASSAY": ("ERROR", "assay.csv"),
    "INTERVAL_FROM_BEFORE_TO_LITHOLOGY": ("ERROR", "lithology.csv"),
    "INTERVAL_FROM_BEFORE_TO_DENSITY": ("ERROR", "density.csv"),
    "INTERVAL_LENGTH_MATCH_ASSAY": ("ERROR", "assay.csv"),
    "INTERVAL_LENGTH_MATCH_LITHOLOGY": ("ERROR", "lithology.csv"),
    "INTERVAL_LENGTH_MATCH_DENSITY": ("ERROR", "density.csv"),
    "INTERVAL_WITHIN_FINAL_DEPTH_ASSAY": ("ERROR", "assay.csv"),
    "INTERVAL_WITHIN_FINAL_DEPTH_LITHOLOGY": ("ERROR", "lithology.csv"),
    "INTERVAL_WITHIN_FINAL_DEPTH_DENSITY": ("ERROR", "density.csv"),
    "INTERVAL_OVERLAP_ASSAY": ("ERROR", "assay.csv"),
    "INTERVAL_OVERLAP_LITHOLOGY": ("ERROR", "lithology.csv"),
    "INTERVAL_OVERLAP_DENSITY": ("WARNING", "density.csv"),
    "INTERVAL_GAP_ASSAY": ("WARNING", "assay.csv"),
    "INTERVAL_GAP_LITHOLOGY": ("WARNING", "lithology.csv"),
    "INTERVAL_GAP_DENSITY": ("INFO", "density.csv"),
    "ASSAY_GRADE_NUMERIC": ("ERROR", "assay.csv"),
    "ASSAY_GRADE_NONNEGATIVE": ("ERROR", "assay.csv"),
    "ASSAY_GRADE_ZERO": ("INFO", "assay.csv"),
    "DENSITY_NUMERIC_POSITIVE": ("ERROR", "density.csv"),
    "DENSITY_COVERAGE": ("INFO", "density.csv"),
    "ALTERATION_UNAVAILABLE": ("INFO", "alteration.csv"),
    "CAMPAIGN_ID_EQUIVALENCE": ("WARNING", "source_table"),
}


@dataclass(frozen=True)
class ValidationFinding:
    """One validation finding with a stable rule identifier and row context."""

    rule_id: str
    severity: str
    table: str
    row_number: int | None
    hole_id: str | None
    field: str | None
    observed_value: str | None
    expected_condition: str


@dataclass(frozen=True)
class ValidationReport:
    """Findings generated by the data contract and M01 validation rules."""

    findings: tuple[ValidationFinding, ...]

    @property
    def is_valid(self) -> bool:
        return not any(finding.severity == "ERROR" for finding in self.findings)


def _add(
    findings: list[ValidationFinding],
    rule_id: str,
    table: str,
    expected_condition: str,
    *,
    row_number: int | None = None,
    hole_id: str | None = None,
    field: str | None = None,
    observed_value: object | None = None,
    severity: str | None = None,
) -> None:
    configured_severity = (
        CONTRACT_RULES.get(rule_id) or VALIDATION_RULES.get(rule_id)
    )
    if severity is None:
        if configured_severity is None:
            raise ValueError(f"No configured severity for rule {rule_id}.")
        severity = configured_severity[0]
    findings.append(
        ValidationFinding(
            rule_id=rule_id,
            severity=severity,
            table=table,
            row_number=row_number,
            hole_id=hole_id,
            field=field,
            observed_value=None if observed_value is None else str(observed_value),
            expected_condition=expected_condition,
        )
    )


def _number(value: str | None) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def _finite_number(value: str | None) -> float | None:
    number = _number(value)
    if number is None or not math.isfinite(number):
        return None
    return number


def _hole_id(row: dict[str, str | None]) -> str | None:
    return row.get("hole_id")


def _validate_contract(inputs: M01Inputs, findings: list[ValidationFinding]) -> None:
    dictionary = inputs.data_dictionary
    missing_columns = DICTIONARY_COLUMNS.difference(dictionary.headers)
    if missing_columns:
        _add(
            findings,
            "CTR_DICTIONARY_SCHEMA",
            "data_dictionary.csv",
            "Dictionary contains all required metadata columns.",
            observed_value=", ".join(sorted(missing_columns)),
            field=",".join(sorted(missing_columns)),
        )
        return

    definitions: dict[str, list[dict[str, str | None]]] = {}
    for row_number, row in enumerate(dictionary.rows, start=2):
        filename = row.get("file")
        column = row.get("column")
        if not filename or not column:
            _add(
                findings,
                "CTR_DICTIONARY_ROW",
                "data_dictionary.csv",
                "Each dictionary row identifies a source file and column.",
                row_number=row_number,
                field="file,column",
                observed_value=f"{filename!r},{column!r}",
            )
            continue
        definitions.setdefault(filename, []).append(row)

    manifest_files = inputs.manifest.get("files")
    if not isinstance(manifest_files, list):
        _add(
            findings,
            "CTR_MANIFEST_FILES",
            "release_manifest.json",
            "'files' is a list containing the loaded source tables.",
            field="files",
            observed_value=manifest_files,
        )
        manifest_files = []

    for filename, table in inputs.tables.items():
        if filename not in manifest_files:
            _add(
                findings,
                "CTR_MANIFEST_FILES",
                "release_manifest.json",
                f"{filename} is listed in the release manifest.",
                field="files",
                observed_value=filename,
            )

        field_definitions = definitions.get(filename, [])
        if not field_definitions:
            _add(
                findings,
                "CTR_DICTIONARY_ROW",
                "data_dictionary.csv",
                f"Definitions exist for all columns in {filename}.",
                field="file",
                observed_value=filename,
            )
            continue

        seen_columns: set[str] = set()
        for definition in field_definitions:
            column = definition["column"] or ""
            if column in seen_columns:
                _add(
                    findings,
                    "CTR_DICTIONARY_DUPLICATE",
                    "data_dictionary.csv",
                    f"{filename}.{column} has one dictionary definition.",
                    field=column,
                    observed_value=filename,
                )
            seen_columns.add(column)

            if definition["dtype"] not in {"string", "float"}:
                _add(
                    findings,
                    "CTR_DICTIONARY_DEFINITION",
                    "data_dictionary.csv",
                    "dtype is 'string' or 'float'.",
                    field=column,
                    observed_value=definition["dtype"],
                )
            if definition["nullable"] not in {"true", "false"}:
                _add(
                    findings,
                    "CTR_DICTIONARY_DEFINITION",
                    "data_dictionary.csv",
                    "nullable is 'true' or 'false'.",
                    field=column,
                    observed_value=definition["nullable"],
                )

        expected_columns = {row["column"] for row in field_definitions}
        actual_columns = set(table.headers)
        for column in sorted(expected_columns - actual_columns):
            _add(
                findings,
                "CTR_SCHEMA_COLUMN",
                filename,
                "Column defined by data_dictionary.csv exists in the table.",
                field=column,
                observed_value="MISSING",
            )
        for column in sorted(actual_columns - expected_columns):
            _add(
                findings,
                "CTR_SCHEMA_COLUMN",
                filename,
                "Every table column is defined in data_dictionary.csv.",
                field=column,
                observed_value="UNDOCUMENTED",
            )

        for row_number, row in enumerate(table.rows, start=2):
            for definition in field_definitions:
                column = definition["column"]
                if column not in table.headers:
                    continue
                value = row.get(column)
                hole_id = _hole_id(row)
                if value is None or not value.strip():
                    if definition["nullable"] == "false":
                        _add(
                            findings,
                            "CTR_REQUIRED_VALUE",
                            filename,
                            "Non-nullable values are not empty.",
                            row_number=row_number,
                            hole_id=hole_id,
                            field=column,
                            observed_value=value,
                        )
                    continue

                if definition["dtype"] == "float":
                    number = _number(value)
                    if number is None:
                        _add(
                            findings,
                            "CTR_VALUE_TYPE",
                            filename,
                            "Value is numeric according to the documented float dtype.",
                            row_number=row_number,
                            hole_id=hole_id,
                            field=column,
                            observed_value=value,
                        )
                    elif not math.isfinite(number):
                        _add(
                            findings,
                            "CTR_VALUE_FINITE",
                            filename,
                            "Numeric value is finite.",
                            row_number=row_number,
                            hole_id=hole_id,
                            field=column,
                            observed_value=value,
                        )

        count_field = MANIFEST_COUNT_FIELDS.get(filename)
        if count_field:
            expected_count = inputs.manifest.get(count_field)
            if (
                not isinstance(expected_count, int)
                or isinstance(expected_count, bool)
                or len(table.rows) != expected_count
            ):
                _add(
                    findings,
                    "CTR_MANIFEST_COUNT",
                    filename,
                    f"Table row count equals integer manifest field {count_field}.",
                    field=count_field,
                    observed_value=f"rows={len(table.rows)}, manifest={expected_count!r}",
                )

        for identity_field in ("dataset_id", "project_id"):
            expected_value = inputs.manifest.get(identity_field)
            if expected_value is None or identity_field not in table.headers:
                continue
            for row_number, row in enumerate(table.rows, start=2):
                if row.get(identity_field) != expected_value:
                    _add(
                        findings,
                        "CTR_MANIFEST_IDENTITY",
                        filename,
                        f"{identity_field} equals manifest value {expected_value!r}.",
                        row_number=row_number,
                        hole_id=_hole_id(row),
                        field=identity_field,
                        observed_value=row.get(identity_field),
                    )

    _validate_stable_identifiers(inputs, findings)
    _validate_hole_references(inputs, findings)


def _validate_stable_identifiers(
    inputs: M01Inputs,
    findings: list[ValidationFinding],
) -> None:
    for filename, field in UNIQUE_IDENTIFIER_FIELDS.items():
        table = inputs.tables.get(filename)
        if table is None or field not in table.headers:
            continue
        seen: set[str] = set()
        for row_number, row in enumerate(table.rows, start=2):
            identifier = row.get(field)
            if identifier is None:
                continue
            if identifier in seen:
                _add(
                    findings,
                    "CTR_STABLE_ID_UNIQUE",
                    filename,
                    f"{field} is unique in {filename}.",
                    row_number=row_number,
                    hole_id=_hole_id(row),
                    field=field,
                    observed_value=identifier,
                )
            seen.add(identifier)


def _collar_lookup(inputs: M01Inputs) -> dict[str, tuple[int, dict[str, str | None]]]:
    collar = inputs.tables.get("collar.csv")
    if collar is None or "hole_id" not in collar.headers:
        return {}
    lookup: dict[str, tuple[int, dict[str, str | None]]] = {}
    for row_number, row in enumerate(collar.rows, start=2):
        hole_id = row.get("hole_id")
        if hole_id is not None and hole_id not in lookup:
            lookup[hole_id] = (row_number, row)
    return lookup


def _validate_hole_references(
    inputs: M01Inputs,
    findings: list[ValidationFinding],
) -> None:
    collar_holes = set(_collar_lookup(inputs))
    for filename, table in inputs.tables.items():
        if filename in {"collar.csv", "survey.csv"} or "hole_id" not in table.headers:
            continue
        for row_number, row in enumerate(table.rows, start=2):
            hole_id = row.get("hole_id")
            if hole_id is not None and hole_id not in collar_holes:
                _add(
                    findings,
                    "CTR_HOLE_REFERENCE",
                    filename,
                    "hole_id references a hole_id present in collar.csv.",
                    row_number=row_number,
                    hole_id=hole_id,
                    field="hole_id",
                    observed_value=hole_id,
                )


def _validate_collar(
    inputs: M01Inputs,
    collar_lookup: dict[str, tuple[int, dict[str, str | None]]],
    findings: list[ValidationFinding],
) -> None:
    table = inputs.tables.get("collar.csv")
    if table is None:
        return
    if "hole_id" in table.headers:
        seen: set[str] = set()
        for row_number, row in enumerate(table.rows, start=2):
            hole_id = row.get("hole_id")
            if hole_id is None:
                continue
            if hole_id in seen:
                _add(
                    findings,
                    "COLLAR_HOLE_ID_UNIQUE",
                    "collar.csv",
                    "hole_id is unique in collar.csv.",
                    row_number=row_number,
                    hole_id=hole_id,
                    field="hole_id",
                    observed_value=hole_id,
                )
            seen.add(hole_id)

    for row_number, row in enumerate(table.rows, start=2):
        hole_id = _hole_id(row)
        if "final_depth_m" in table.headers:
            value = row.get("final_depth_m")
            depth = _finite_number(value)
            if depth is None or depth <= 0:
                _add(
                    findings,
                    "COLLAR_FINAL_DEPTH_POSITIVE",
                    "collar.csv",
                    "final_depth_m is a finite numeric value greater than zero.",
                    row_number=row_number,
                    hole_id=hole_id,
                    field="final_depth_m",
                    observed_value=value,
                )

        for coordinate in ("x", "y", "z"):
            if coordinate not in table.headers:
                continue
            value = row.get(coordinate)
            if _finite_number(value) is None:
                _add(
                    findings,
                    "COLLAR_COORDINATE_FINITE",
                    "collar.csv",
                    f"{coordinate} is numeric and finite.",
                    row_number=row_number,
                    hole_id=hole_id,
                    field=coordinate,
                    observed_value=value,
                )


def _validate_survey(
    inputs: M01Inputs,
    collar_lookup: dict[str, tuple[int, dict[str, str | None]]],
    findings: list[ValidationFinding],
) -> None:
    table = inputs.tables.get("survey.csv")
    if table is None:
        return

    by_hole: dict[str, list[tuple[int, dict[str, str | None], float | None]]] = {}
    for row_number, row in enumerate(table.rows, start=2):
        hole_id = _hole_id(row)
        depth_value = row.get("depth_m")
        depth = _finite_number(depth_value)

        if hole_id not in collar_lookup:
            _add(
                findings,
                "SURVEY_HOLE_REFERENCE",
                "survey.csv",
                "survey.hole_id exists in collar.csv.",
                row_number=row_number,
                hole_id=hole_id,
                field="hole_id",
                observed_value=hole_id,
            )

        if "depth_m" in table.headers:
            if depth is None or depth < 0:
                _add(
                    findings,
                    "SURVEY_DEPTH_NONNEGATIVE",
                    "survey.csv",
                    "depth_m is finite and greater than or equal to zero.",
                    row_number=row_number,
                    hole_id=hole_id,
                    field="depth_m",
                    observed_value=depth_value,
                )
            elif hole_id is not None:
                by_hole.setdefault(hole_id, []).append((row_number, row, depth))

        for field in ("azimuth_deg", "dip_deg"):
            if field in table.headers and _finite_number(row.get(field)) is None:
                _add(
                    findings,
                    "SURVEY_ORIENTATION_FINITE",
                    "survey.csv",
                    f"{field} is numeric and finite.",
                    row_number=row_number,
                    hole_id=hole_id,
                    field=field,
                    observed_value=row.get(field),
                )

    for hole_id, stations in by_hole.items():
        depths = [station[2] for station in stations]
        if not any(depth == 0 for depth in depths):
            _add(
                findings,
                "SURVEY_DEPTH_ZERO_STATION",
                "survey.csv",
                "Each collar hole has a survey station at depth_m = 0.",
                hole_id=hole_id,
                field="depth_m",
                observed_value=depths,
            )

        seen_depths: set[float] = set()
        previous_depth: float | None = None
        for row_number, row, depth in stations:
            if depth in seen_depths or (
                previous_depth is not None and depth < previous_depth
            ):
                _add(
                    findings,
                    "SURVEY_DEPTH_ORDERED",
                    "survey.csv",
                    "Survey depths are strictly increasing and have no duplicates "
                    "within each hole.",
                    row_number=row_number,
                    hole_id=hole_id,
                    field="depth_m",
                    observed_value=depth,
                )
            seen_depths.add(depth)
            previous_depth = depth

            collar_record = collar_lookup.get(hole_id)
            if collar_record is None:
                continue
            collar_row = collar_record[1]
            final_depth = _finite_number(collar_row.get("final_depth_m"))
            if (
                final_depth is not None
                and depth > final_depth + NUMERIC_ROUNDING_TOLERANCE_M
            ):
                _add(
                    findings,
                    "SURVEY_DEPTH_WITHIN_COLLAR",
                    "survey.csv",
                    "depth_m does not exceed collar.final_depth_m "
                    f"(rounding tolerance {NUMERIC_ROUNDING_TOLERANCE_M:g} m).",
                    row_number=row_number,
                    hole_id=hole_id,
                    field="depth_m",
                    observed_value=depth,
                )

    for hole_id, (collar_row_number, _) in collar_lookup.items():
        if hole_id not in by_hole:
            _add(
                findings,
                "SURVEY_DEPTH_ZERO_STATION",
                "survey.csv",
                "Each collar hole has at least one survey station at depth_m = 0.",
                row_number=None,
                hole_id=hole_id,
                field="depth_m",
                observed_value="no survey rows",
            )


def _interval_rule_id(base: str, filename: str) -> str:
    suffix = filename.removesuffix(".csv").upper()
    return f"{base}_{suffix}"


def _validate_intervals(
    inputs: M01Inputs,
    collar_lookup: dict[str, tuple[int, dict[str, str | None]]],
    findings: list[ValidationFinding],
) -> None:
    filenames = ("assay.csv", "lithology.csv", "density.csv")
    for filename in filenames:
        table = inputs.tables.get(filename)
        if table is None:
            continue
        valid_rows_by_hole: dict[
            str, list[tuple[int, dict[str, str | None], float, float]]
        ] = {}

        for row_number, row in enumerate(table.rows, start=2):
            hole_id = _hole_id(row)
            start_value = row.get("from_m")
            end_value = row.get("to_m")
            start = _finite_number(start_value)
            end = _finite_number(end_value)
            length = _finite_number(row.get("length_m"))

            if start is None or end is None or start >= end:
                _add(
                    findings,
                    _interval_rule_id("INTERVAL_FROM_BEFORE_TO", filename),
                    filename,
                    "from_m and to_m are finite numeric values and from_m is "
                    "strictly less than to_m.",
                    row_number=row_number,
                    hole_id=hole_id,
                    field="from_m,to_m",
                    observed_value=f"{start_value},{end_value}",
                )
            elif hole_id is not None:
                valid_rows_by_hole.setdefault(hole_id, []).append(
                    (row_number, row, start, end)
                )

            if start is not None and end is not None:
                if length is None or abs((end - start) - length) > (
                    NUMERIC_ROUNDING_TOLERANCE_M
                ):
                    _add(
                        findings,
                        _interval_rule_id("INTERVAL_LENGTH_MATCH", filename),
                        filename,
                        "length_m equals to_m - from_m within numeric rounding "
                        f"tolerance {NUMERIC_ROUNDING_TOLERANCE_M:g} m.",
                        row_number=row_number,
                        hole_id=hole_id,
                        field="length_m",
                        observed_value=(
                            f"length_m={row.get('length_m')}, "
                            f"to_m-from_m={end - start}"
                        ),
                    )

                collar_record = collar_lookup.get(hole_id or "")
                if collar_record is not None:
                    final_depth = _finite_number(
                        collar_record[1].get("final_depth_m")
                    )
                    if final_depth is not None and (
                        start < -NUMERIC_ROUNDING_TOLERANCE_M
                        or end > final_depth + NUMERIC_ROUNDING_TOLERANCE_M
                    ):
                        _add(
                            findings,
                            _interval_rule_id(
                                "INTERVAL_WITHIN_FINAL_DEPTH", filename
                            ),
                            filename,
                            "Interval lies within [0, collar.final_depth_m] "
                            f"within numeric rounding tolerance "
                            f"{NUMERIC_ROUNDING_TOLERANCE_M:g} m.",
                            row_number=row_number,
                            hole_id=hole_id,
                            field="from_m,to_m",
                            observed_value=f"{start_value},{end_value}",
                        )

            if filename == "assay.csv":
                for grade_field in ("cu_pct", "mo_pct", "au_gt"):
                    if grade_field not in table.headers:
                        continue
                    value = row.get(grade_field)
                    grade = _finite_number(value)
                    if grade is None:
                        _add(
                            findings,
                            "ASSAY_GRADE_NUMERIC",
                            filename,
                            f"{grade_field} is numeric and finite.",
                            row_number=row_number,
                            hole_id=hole_id,
                            field=grade_field,
                            observed_value=value,
                        )
                    elif grade < 0:
                        _add(
                            findings,
                            "ASSAY_GRADE_NONNEGATIVE",
                            filename,
                            f"{grade_field} is greater than or equal to zero.",
                            row_number=row_number,
                            hole_id=hole_id,
                            field=grade_field,
                            observed_value=value,
                        )
                    elif grade == 0:
                        _add(
                            findings,
                            "ASSAY_GRADE_ZERO",
                            filename,
                            f"Zero {grade_field} assay is recorded for review; "
                            "no below-detection interpretation is assumed.",
                            row_number=row_number,
                            hole_id=hole_id,
                            field=grade_field,
                            observed_value=value,
                        )

            if filename == "density.csv" and "density_t_m3" in table.headers:
                value = row.get("density_t_m3")
                density = _finite_number(value)
                if density is None or density <= 0:
                    _add(
                        findings,
                        "DENSITY_NUMERIC_POSITIVE",
                        filename,
                        "density_t_m3 is numeric, finite, and greater than zero.",
                        row_number=row_number,
                        hole_id=hole_id,
                        field="density_t_m3",
                        observed_value=value,
                    )

        for hole_id, intervals in valid_rows_by_hole.items():
            intervals.sort(key=lambda item: (item[2], item[3], item[0]))
            furthest_end = intervals[0][3]
            furthest_row = intervals[0][0]
            first_start = intervals[0][2]
            if first_start > NUMERIC_ROUNDING_TOLERANCE_M:
                _add(
                    findings,
                    _interval_rule_id("INTERVAL_GAP", filename),
                    filename,
                    "Interval gap status is reported with table-specific severity.",
                    row_number=intervals[0][0],
                    hole_id=hole_id,
                    field="from_m",
                    observed_value=f"previous_to=0; current_from={first_start}; "
                    f"gap_m={first_start}",
                )
            for row_number, _, start, end in intervals[1:]:
                delta = start - furthest_end
                if delta < -NUMERIC_ROUNDING_TOLERANCE_M:
                    rule_id = _interval_rule_id("INTERVAL_OVERLAP", filename)
                    _add(
                        findings,
                        rule_id,
                        filename,
                        "Intervals do not overlap within this hole.",
                        row_number=row_number,
                        hole_id=hole_id,
                        field="from_m,to_m",
                        observed_value=(
                            f"overlap_with_row={furthest_row}; "
                            f"previous_to={furthest_end}; current_from={start}"
                        ),
                    )
                elif delta > NUMERIC_ROUNDING_TOLERANCE_M:
                    rule_id = _interval_rule_id("INTERVAL_GAP", filename)
                    _add(
                        findings,
                        rule_id,
                        filename,
                        "Interval gap status is reported with table-specific severity.",
                        row_number=row_number,
                        hole_id=hole_id,
                        field="from_m",
                        observed_value=(
                            f"previous_to={furthest_end}; current_from={start}; "
                            f"gap_m={delta}"
                        ),
                    )
                if end > furthest_end:
                    furthest_end = end
                    furthest_row = row_number

            collar_record = collar_lookup.get(hole_id)
            final_depth = (
                _finite_number(collar_record[1].get("final_depth_m"))
                if collar_record is not None
                else None
            )
            if (
                final_depth is not None
                and final_depth - furthest_end > NUMERIC_ROUNDING_TOLERANCE_M
            ):
                _add(
                    findings,
                    _interval_rule_id("INTERVAL_GAP", filename),
                    filename,
                    "Interval gap status is reported with table-specific severity.",
                    row_number=furthest_row,
                    hole_id=hole_id,
                    field="to_m",
                    observed_value=(
                        f"previous_to={furthest_end}; final_depth={final_depth}; "
                        f"gap_m={final_depth - furthest_end}"
                    ),
                )

        for hole_id, (_, collar_row) in collar_lookup.items():
            if hole_id in valid_rows_by_hole:
                continue
            final_depth = _finite_number(collar_row.get("final_depth_m"))
            if final_depth is not None and final_depth > NUMERIC_ROUNDING_TOLERANCE_M:
                _add(
                    findings,
                    _interval_rule_id("INTERVAL_GAP", filename),
                    filename,
                    "Interval gap status is reported with table-specific severity.",
                    hole_id=hole_id,
                    field="from_m,to_m",
                    observed_value=f"no intervals; uncovered_depth={final_depth}",
                )


def _validate_density_coverage(
    inputs: M01Inputs,
    collar_lookup: dict[str, tuple[int, dict[str, str | None]]],
    findings: list[ValidationFinding],
) -> None:
    density_table = inputs.tables.get("density.csv")
    if density_table is None:
        return
    intervals_by_hole: dict[str, list[tuple[float, float]]] = {}
    first_density_row: dict[str, int] = {}
    for row_number, row in enumerate(density_table.rows, start=2):
        hole_id = row.get("hole_id")
        start = _finite_number(row.get("from_m"))
        end = _finite_number(row.get("to_m"))
        if hole_id is not None and start is not None and end is not None and start < end:
            intervals_by_hole.setdefault(hole_id, []).append((start, end))
            first_density_row.setdefault(hole_id, row_number)

    for hole_id, (row_number, collar_row) in collar_lookup.items():
        final_depth = _finite_number(collar_row.get("final_depth_m"))
        if final_depth is None or final_depth <= 0:
            continue

        clipped = sorted(
            (
                max(0.0, start),
                min(final_depth, end),
            )
            for start, end in intervals_by_hole.get(hole_id, [])
            if end > 0 and start < final_depth
        )
        covered_length = 0.0
        covered_end = 0.0
        for start, end in clipped:
            if end <= start:
                continue
            if start > covered_end:
                covered_length += end - start
            elif end > covered_end:
                covered_length += end - covered_end
            covered_end = max(covered_end, end)

        coverage_percent = 100.0 * covered_length / final_depth
        sample_count = len(intervals_by_hole.get(hole_id, []))
        _add(
            findings,
            "DENSITY_COVERAGE",
            "density.csv",
            "Informational union coverage of valid density intervals against "
            "[0, collar.final_depth_m]; no acceptance threshold is defined.",
            row_number=first_density_row.get(hole_id),
            hole_id=hole_id,
            field="from_m,to_m",
            observed_value=(
                f"{covered_length:.9g} m of {final_depth:.9g} m "
                f"({coverage_percent:.6g}%); samples={sample_count}"
            ),
        )


def _validate_alteration(inputs: M01Inputs, findings: list[ValidationFinding]) -> None:
    table = inputs.tables.get("alteration.csv")
    if table is not None and not table.rows:
        _add(
            findings,
            "ALTERATION_UNAVAILABLE",
            "alteration.csv",
            "Alteration observations are available; empty release means data is "
            "unavailable, not that alteration is geologically absent.",
            field="records",
            observed_value=0,
        )


def _validate_campaign_equivalence(
    inputs: M01Inputs,
    findings: list[ValidationFinding],
) -> None:
    manifest_campaigns = inputs.manifest.get("campaigns")
    if not isinstance(manifest_campaigns, list):
        return
    expected_campaigns = {str(campaign) for campaign in manifest_campaigns}

    for filename, table in inputs.tables.items():
        if "campaign_id" not in table.headers:
            continue
        first_row_by_campaign: dict[str, int] = {}
        for row_number, row in enumerate(table.rows, start=2):
            campaign_id = row.get("campaign_id")
            if campaign_id is not None:
                first_row_by_campaign.setdefault(campaign_id, row_number)

        for campaign_id, row_number in first_row_by_campaign.items():
            normalized = (
                f"C{campaign_id.removeprefix('CAMPAIGN_')}"
                if campaign_id.startswith("CAMPAIGN_")
                else campaign_id
            )
            if campaign_id in expected_campaigns:
                continue
            expected_condition = (
                f"campaign_id uses the exact manifest identifier; the possible "
                f"equivalence {normalized!r} remains pending confirmation."
                if normalized in expected_campaigns
                else "campaign_id matches a campaign declared in the manifest."
            )
            _add(
                findings,
                "CAMPAIGN_ID_EQUIVALENCE",
                filename,
                expected_condition,
                row_number=row_number,
                hole_id=(
                    table.rows[row_number - 2].get("hole_id")
                    if row_number - 2 < len(table.rows)
                    else None
                ),
                field="campaign_id",
                observed_value=campaign_id,
                severity="WARNING",
            )


def validate_m01_inputs(inputs: M01Inputs) -> ValidationReport:
    """Run the data-contract and approved pre-desurvey validation rules."""

    findings: list[ValidationFinding] = []
    _validate_contract(inputs, findings)
    collar_lookup = _collar_lookup(inputs)
    _validate_collar(inputs, collar_lookup, findings)
    _validate_survey(inputs, collar_lookup, findings)
    _validate_intervals(inputs, collar_lookup, findings)
    _validate_density_coverage(inputs, collar_lookup, findings)
    _validate_alteration(inputs, findings)
    _validate_campaign_equivalence(inputs, findings)
    return ValidationReport(tuple(findings))
